---
- hosts: "webserver"
  vars:
    packagename: "nginx"
  tasks:
  - name: "set the nginx repo"
    apt_repository:
      repo: "ppa:nginx/stable"
  - name: "install nginx package"
    apt:
      name: "{{ packagename }}"
      state: "latest"
  - name: "copy nginx.conf file "   
    copy:
      src: nginx.conf
      dest: "/etc/nginx/nginx.conf"
    notify: "restart the nginx service"  
  - name: "generate index.html file "   
    template:
      src: index.html.j2
      dest: "/var/www/html/index.nginx-debian.html"
    notify: "restart the nginx service"  
  - name: "start the nginx service"   
    service:
      name: "{{ packagename }}"
      state: "started"      
  handlers:
  - name: "restart the nginx service"
    service:
      name: "{{ packagename }}"
      state: "restarted"
